config/routes.rb
# Rails.application.routes.draw do
#   root to: 'about#about'
#   devise_for :user
#   get
# end

Rails.application.routes.draw do

  devise_for :user
  root to: 'about#about'

  get "/skills", to: "skills#index"
  #verbo, texto,hacia  controlador#
  get "/contact", to: "contact#contact_us"
  get "/projects", to: "projects#projects"

  namespace :admins do 

    get "/", to: 'about#about'
    get "/about/:id/edit", to: 'about#edit'
    get "/skills", to: "skills#index"
    get "/projects", to: "projects#projects"

  end

end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    has_one :contact_type
  
end

app/models/contact_type.rb
class ContactType < ApplicationRecord
    belongs_to :contact 
end

app/models/proyect.rb
class Proyect < ApplicationRecord
    has_many :tech 
    has_one :usr  
end

app/models/skill.rb
class Skill < ApplicationRecord
 belongs_to :usrs
 has_one :skill_type
end

app/models/skill_type.rb
class SkillType < ApplicationRecord
    belongs_to :skill
end

app/models/tech.rb
class Tech < ApplicationRecord
 belongs_to :projects   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usr.rb
class Usr < ApplicationRecord
has_many :skill_type
has_many :projects 
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def contact
        
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
    def projects
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def index
        
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def is_admin_path?
request.fullpath.include?("admins") 
end 


end




#PUED DEFINIR METODOS Y LLAMARLOS EN LA VISTA

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/_footer.html.erb
<footer>
<nav>
  <ul>
   <li>
    <%= link_to "Home", root_path %>
   </li>
      <li>
    <%= link_to "Projects", projects_path %>
   </li>
   <li>
    <%= link_to "skills", skills_path %>
   </li>
    <li>
    <%= link_to "contact", contact_path %>
   </li>
  </ul>
</nav>
</footer>

app/views/layouts/_navbar.html.erb
<header>
<nav>

  <% if is_admin_path? %>

    <ul class="Navbar">

      <li>
      <%= link_to "Home", admins_path %>
      </li>
      <li>
      <%= link_to "Projects", admins_projects_path %>
      </li>
      <li>
      <%= link_to "skills", admins_skills_path %>
      </li>
    
    </ul>

  <% else %>

    <ul class="Navbar">

      <li>
      <%= link_to "Home", root_path %>
      </li>
      <li>
      <%= link_to "Projects", projects_path %>
      </li>
      <li>
      <%= link_to "skills", skills_path %>
      </li>
      <li>
      <%= link_to "contact", contact_path %>
      </li>

    </ul>

  <% end %>

</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <%= yield %>
    

  </body>
</html>